# CircleCI configuration file
version: 2.1

commands:
  clean_and_build:
    description: "Clean and build example document."
    parameters:
      engine:
        description: "Which engine to use for compilation."
        default: "pdflatex"
        type: string
    steps:
      - run:
          name: clean build
          command: make clean
      - run:
          name: build with << parameters.engine >>
          command: make
          environment:
            LATEX: << parameters.engine >>

jobs:
  lint:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run: make lint
  check_build:
    docker:
      - image: cimg/base:current
    description: "Set up LaTeX environment and build document against pdfLaTeX, luaLaTeX, and XeTeX."
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt update -y && sudo apt install -y libfontconfig1 make perl-doc wget
      # - restore_cache:
      #     key: v2-{{ checksum "packages.txt" }}
      - run:
          name: Install minimal TeXLive
          command: sudo ./bin/install-texlive
      - run:
          name: Install package dependencies
          command: sudo ./bin/install-packages packages.txt
      # - save_cache:
      #     key: v2-{{ checksum "packages.txt" }}
      #     paths:
      #       - ~/.texlive
      #       - /srv/texlive
      - run:
          name: Add TeXLive to PATH
          command: echo 'export PATH="/srv/texlive/bin/x86_64-linux:${PATH}"' >>$BASH_ENV
      - clean_and_build:
          engine: pdflatex
      - clean_and_build:
          engine: lualatex
      - clean_and_build:
          engine: xelatex

workflows:
  check_pr:
    jobs:
      - lint
      - check_build
